### ISSUE TITLE
merge into metasploit project

### ISSUE THREAD

**Issue by phra** [b4rtik/metasploit-execute-assembly#1]
Hi,

nice project! are you planning to merge it into the main repository?

**Comment by b4rtik** [comment]
Hi,
I think it need 2 major thins before submit to Rapid 7:

1. testing on 32bit platform
2. support for .Net framework 3.5 for more compatibility on target

After that I plan to ask if they are interested

Reagards

**Comment by akefallonitis** [comment]
Any update on merging ?

**Comment by b4rtik** [comment]
I can finally say YES, the process towards a PR has started and I am working with @TheColonial to merge this module into Metasploit. Fingers crossed.

**Comment by akefallonitis** [comment]
👍  Nice and thank you

**Comment by phra** [comment]
@b4rtik @OJ see https://github.com/rapid7/metasploit-framework/pull/12391 and https://twitter.com/phraaaaaaa/status/1179785130539458561
