### ISSUE TITLE
execute-assembly problem

### ISSUE THREAD

**Issue by akefallonitis** [b4rtik/metasploit-execute-assembly#2]
I get this error when i try to execute SafetyKatz.exe with execute-assembly.
[-] Post failed: RuntimeError Cannot find the ReflectiveLoader entry point in /usr/share/metasploit-framework/data/post/execute-assembly/HostingCLRx64.dll

Did i miss something on installation ?

**Comment by b4rtik** [comment]
I have never seen this error.
There seems to have been a problem with compiling the dll. Did you have any error during the compiling process?

Did you use make.bat or did you compile with VS?

The version of SO that Meterpreter is running on?
