### ISSUE TITLE
about .net version

### ISSUE THREAD

**Issue by FunnyWolf** [b4rtik/metasploit-execute-assembly#3]
it seems like this module just support .net 2.0 and .net 4.0
`char sig_40[] = { 0x76,0x34,0x2E,0x30,0x2E,0x33,0x30,0x33,0x31,0x39 };
char sig_20[] = { 0x76,0x32,0x2E,0x30,0x2E,0x35,0x30,0x37,0x32,0x37 };`
Can. NET3.5 be added to support.  because many tools have a minimum version of .NET3.5

**Comment by b4rtik** [comment]
The reference is not to the Framework but to the CLR. Assembly that target 3.5 Framework needs the CLR 2.0.

http://b4rtik.blogspot.com/2019/10/execute-assembly-via-meterpreter.html

**Comment by FunnyWolf** [comment]
> The reference is not to the Framework but to the CLR. Assembly that target 3.5 Framework needs the CLR 2.0.
> 
> http://b4rtik.blogspot.com/2019/10/execute-assembly-via-meterpreter.html

ok,I will build an .net3.5 program an try this module. by the way ,this module is awesome!
