### ISSUE TITLE
Recent changes to the payload

### ISSUE THREAD

**Issue by osok** [b4rtik/metasploit-execute-assembly#4]
I see that you have removed the 1 MB limit and modified the structure of the payload.

From what I can tell the payload is
4 bytes = size of the assembly
4 bytes = size of the params
1 byte = amsi bypass 0x00 don't bypass or 0x01 do bypass
n bytes = parameters
m bytes = assembly

I want to verify that is correct. or is the length of parameters inclusive of the 1 byte for amsi bypass?

I ask because I see, in HostingCLR

`	unsigned char *allData = (unsigned char*)malloc(raw_assembly_length * sizeof(unsigned char)+ raw_args_length * sizeof(unsigned char) + 8 * sizeof(unsigned char));`

I think that shouldbe a + 9 not + 8. It doesn't seem to account for the amsi byte.

same here:
`	ReadProcessMemory(GetCurrentProcess(), lpPayload , allData, raw_assembly_length + raw_args_length + 8, &readed);`

I see that you break apart here:

```
	unsigned char *offsetamsi = allData + 8;
	//Store amsi flag 
	// Read the amsi setting of the provided payload into the amsiflag variable
	// if 0x01 then it will run the AMSI bypass
	memcpy(amsiflag, offsetamsi, 1);
	
	//Taking pointer to args 
	//  arguments are the 10th byte to the (10+size of arguments) byte
	unsigned char *offsetargs = allData + 9;
	//Store parameters 
	memcpy(arg_s, offsetargs, sizeof(arg_s));

	//Taking pointer to assembly
	unsigned char *offset = allData + raw_args_length + 9;
	//Store assembly
	memcpy(pvData, offset, raw_assembly_length);

```
Here is it appears that the length of the params is independent of the amsi flag.

**Comment by b4rtik** [comment]
Hi @osok,
thanks, you are right and for some strange reason this error had never given me problems. I did a quick test and it seems to be working properly now.

**Comment by osok** [comment]
I got my go code working with it.  Well, I modified https://github.com/lesnuages/go-execute-assembly and made a pull request to his repo, with the changes.  So not totally my code.  :-)
