### ISSUE TITLE
do not work on msf module

### ISSUE THREAD

**Issue by FunnyWolf** [b4rtik/metasploit-execute-assembly#5]
when i try to use msf module to get assembly output ,it do not work well (can not get output).
![image](https://user-images.githubusercontent.com/17685281/76509322-cc0eae00-648a-11ea-91e0-5bf8725b5379.png)

when i use the same HostingCLRx64.dll  and run assembly with "go-execute-assembly",it is just good.
![image](https://user-images.githubusercontent.com/17685281/76509521-1bed7500-648b-11ea-8264-48383c86a195.png)

maybe something wrong in msf module?

**Comment by b4rtik** [comment]
As you can see from the second line of the output, the module is used with a configuration that does not allow to recover the output.

Could you send the output of the options command?

I think the parameter you need to configure is WAIT, to retrieve the output it must be greater than 0

**Comment by FunnyWolf** [comment]
> As you can see from the second line of the output, the module is used with a configuration that does not allow to recover the output.
> 
> Could you send the output of the options command?
> 
> I think the parameter you need to configure is WAIT, to retrieve the output it must be greater than 0

thank you for reply，this time i set wait =10, i still can not get ouput.
![image](https://user-images.githubusercontent.com/17685281/76517724-cfa93180-6498-11ea-9d5c-0099ed3ec876.png)

is there a way that we can add some logs on ruby or HostingCLR to help us debug?

**Comment by FunnyWolf** [comment]
i try to debug hostingclr and this is the error infomation
![image](https://user-images.githubusercontent.com/17685281/76638050-c5fdf780-6586-11ea-8c27-71cda1ee1c99.png)

**Comment by b4rtik** [comment]
I did a quick test and it seems to be something related to SafatyKatz in particular.

I tried on the same session to run Seatbelt first and then SafetyKatz.

Seatbelt works SafetyKatz no.

The first thing to check is if you have the same behavior by disabling Defender.

**Comment by FunnyWolf** [comment]
everytime i try msf module, it failed on load_3.
then i try  "go-execute-assembly" for muit times ,first time works fine,it will failed on the second times,failed on invoke_3(so maybe it is not the problem on SafetyKatz or Seatbelt but who run first). 

i also try "https://github.com/etormadiv/HostingCLR" and hard code assembly in source code,it works everytime. 

so i think maybe there is something wrong in ReflectiveLoader?

**Comment by b4rtik** [comment]
Do you mean that you have the same behavior with Seatbelt for example?
